language: ruby

sudo: false

cache: bundler

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3

before_install:
  # Keep track of which version of node and phantomjs we're running the specs against
  - node -v
  - phantomjs -v
